import { describe, expect, it } from "vitest";
import type { Token } from "../src/parse/types.ts";
import {
  DEPREL_INVENTORY,
  deprelJa,
  deprelMenuGroups,
  domainMenuValues,
  EMPTY_FIELD_LABEL,
  fieldLabel,
  posChipParts,
  posMenuPrefixes,
  senseMenuValues,
  uposJa,
  editableTag,
} from "../src/render/tokenInspector.ts";
import {
  XPOS_INVENTORY,
  domainsUnder,
  sensesUnder,
  uposForXpos,
  withDomain,
  withPrefix,
  withSense,
  xposMenuPrefixes,
  xposPrefixes,
  xposesUnder,
} from "../src/parse/xpos.ts";

/** The retag menus' inventories against the sources they claim to come from,
 * and the adjective — which is still the awkward category and is awkward in a
 * new way.
 *
 * ── Where the expectations come from, and what changed about that ─────────
 * They used to come from the wheel: `public/wasm/wheels/
 * lzh_sud_kyoto-0.3.2-py3-none-any.whl` → `lzh_sud_kyoto/
 * lzh_sud_kyoto-0.3.2/meta.json`, whose `labels.morphologizer` held 157
 * feature bundles over 15 distinct `POS=` values, and those 15 were what the
 * 品詞 menu offered.
 *
 * The 品詞 menu does not offer UPOS any more. It offers the treebank's own
 * four-field xpos, so the authority for *that* menu is now
 * `src/parse/xpos-inventory.json` — generated by
 * `scripts/build-xpos-inventory.py` off the whole Kyoto treebank, 533 362
 * tokens, 121 tags under 11 syntactic prefixes. The relation menu is
 * untouched and `labels.parser` is still its authority, so `PARSER_DEPRELS`
 * below stays exactly as it was.
 *
 * **The wheel is not silent about xpos, and is deliberately not consulted.**
 * It has a `tagger` beside the morphologiser, and its label set is 146
 * entries of the form `<field index>,<value>` — 4 first fields, 12 品詞, 46
 * domains, 84 senses. The model composes the four rather than choosing among
 * whole tags, so what it *can* emit is a product of 4 × 12 × 46 × 84 and not a
 * list; one of its twelve 品詞, 文字, heads no attested tag at all. A menu of
 * everything it could spell is 185 472 rows. So the menu offers what has been
 * written rather than what could be, and a token wearing something else keeps
 * it — which is the `current` fallback these tests spend most of their length
 * on, exactly as the old ones did for `DET` and `X`.
 *
 * Counts are written out as literals here rather than recomputed, which is the
 * same discipline this file always kept: a figure that recomputes itself
 * cannot fail, and the point of a figure is that a change to the inventory has
 * to be a deliberate change to this line. */
const PARSER_DEPRELS = [
  "ROOT", "cc", "clf", "comp:aux", "comp:obj", "comp:obl", "comp:obl@lmod", "comp:pred", "comp@expl",
  "compound", "compound@redup", "conj:coord", "conj:coord@emb", "dep", "det", "discourse", "discourse@sp",
  "dislocated", "flat", "flat@foreign", "flat@vv", "list", "mod", "mod@lmod", "mod@tmod", "parataxis",
  "punct", "subj", "udep", "udep@lmod", "udep@tmod", "unk", "unk@expl", "vocative",
];

/** The eleven 品詞 the treebank's tags are filed under, in the order the menu
 * puts them — which is **the handbook's order and no longer the corpus's**.
 *
 * The reader's rule: *"Always sort menu items in the order found in
 * traditional grammar handbooks."* It was commonest-first, and that order is
 * still what the corpus says and still what `xposPrefixes` returns; the menu
 * now takes `xposMenuPrefixes` instead. The convention, its sources and the
 * two 品詞 the tradition does not name (接尾辞 and 記号, which take the tail in
 * the frequency order they had) are recorded at `HANDBOOK_ORDER` in xpos.ts,
 * and the two orders are pinned separately in tests/xpos.test.ts. Written out
 * here because this file's whole discipline is that a change to the inventory
 * has to be a deliberate change to a line of it. */
const XPOS_HEADINGS = [
  "名詞", "代名詞", "動詞", "助動詞", "数詞", "副詞", "前置詞", "助詞", "感嘆詞", "記号", "接尾辞",
];

const token = (over: Partial<Token> = {}): Token => ({
  id: 0, text: "高", lemma: "高", pos: "VERB", xpos: "v,動詞,描写,形質", dep: "mod", head: 1, ...over,
});

/** The three category menus for a given token, each as the list of field
 * values it offers. Defaults to the ordinary case: a token wearing an attested
 * tag under an attested 品詞. */
const prefixes = (over: Partial<Token> = {}) => posMenuPrefixes(token(over));
const domains = (over: Partial<Token> = {}) => domainMenuValues(token(over));
const senses = (over: Partial<Token> = {}) => senseMenuValues(token(over));

/** A token bearing the commonest tag the menus will actually offer under
 * `prefix` — which is `xposesUnder`'s first element for ten of the eleven 品詞
 * and *not* for 記号, whose commonest is 句点, a mark. Used to put a token
 * under a given 品詞 without the "keep the token's own value" rule quietly
 * adding an extra row to the menu being examined. */
const under = (prefix: string): Partial<Token> => ({
  xpos: xposesUnder(prefix).find((xpos) => !UNEDITABLE_XPOS.includes(xpos))!,
});

/** Every tag reachable by walking all three menus from every 品詞 — the thing
 * the one flat menu used to be, and now only ever reachable three levels at a
 * time. Assembled here rather than in the source, because no screen shows it:
 * what it is for is asserting that the split menus between them still cover
 * the inventory. */
const reachable = () => {
  const found = new Set<string>();
  for (const prefix of prefixes()) {
    // What picking that 品詞 writes, which is a landing in its own right: a
    // 品詞 whose semantic fields are both `*` (接尾辞, 感嘆詞) has no lower
    // menu and is reached at this level or not at all.
    // The same predicate the menu itself passes — imported rather than
    // restated, so the walk cannot drift from what a click actually does. It
    // is what makes 記号 land on `s,記号,一般,*` instead of on a full stop.
    const base = withPrefix(token().xpos, prefix, (x) => editableTag(x, token()));
    found.add(base);
    for (const domain of domains({ xpos: base })) {
      const tagged = withDomain(base, domain);
      found.add(tagged);
      for (const sense of senses({ xpos: tagged })) found.add(withSense(tagged, sense));
    }
  }
  return [...found];
};

/** Every relation the menu offers, likewise. */
const offeredRels = () =>
  deprelMenuGroups().flatMap(([, rows]) => rows.flatMap((r) => r.segments.filter((sg) => sg.kind === "relation").map((sg) => sg.value)));

/** What each menu hides because it names a token the reader can never be
 * editing. `resolveEntry` returns null for `pos === "PUNCT"`, so a mark draws
 * no chip and no arrow and neither menu can be opened on one — confirmed on
 * the page as well as in that function. A row that writes `PUNCT` could
 * therefore only ever have turned some *other* character into a mark, which is
 * a one-way edit (the cell stops resolving, so the menu cannot be reopened to
 * undo it); `punct` could only ever have said that an ordinary character
 * stands to its head as punctuation does.
 *
 * The part-of-speech half is now a *derived* hiding: what is filtered is the
 * row whose `uposForXpos` is `PUNCT`, not a list of xpos strings. Five rows
 * are, all of them under 記号, and they are named here so that a sixth
 * appearing is a visible change rather than a silent one. */
const UNEDITABLE_UPOS = ["PUNCT"];
const UNEDITABLE_XPOS = [
  "s,記号,*,*", "s,記号,句点,*", "s,記号,括弧閉,*", "s,記号,括弧開,*", "s,記号,読点,*",
];
const UNEDITABLE_DEPRELS = ["punct"];

describe("the three category menus offer what the treebank writes, and nothing else", () => {
  it("offers all eleven 品詞, 記号 included, because the repair now avoids the mark", () => {
    // The first menu, and it is the corpus's own list in the corpus's own
    // order; nothing here files or sorts.
    //
    // **記号 used to be missing and no longer is.** `withPrefix` falls back to
    // a 品詞's commonest tag where the old semantics have no meaning under it,
    // and 記号's commonest is `s,記号,句点,*` — a full stop, 42,983 of its
    // 101,556 — so picking 記号 wrote PUNCT, and the row was then filtered out
    // by the same policy that hides any uneditable result. The fix was to give
    // that policy to the repair as well as to the rows: `withPrefix` takes an
    // `accept` predicate, this menu passes `editableTag`, and 記号 lands on
    // `s,記号,一般,*` — SYM, which resolves like any other token.
    // The same eleven the corpus yields, in the handbook's order rather than
    // the corpus's — asserted as both facts, so that neither can drift into
    // the other.
    expect(prefixes()).toEqual([...xposMenuPrefixes()]);
    expect([...prefixes()].sort()).toEqual([...xposPrefixes()].sort());
    expect(prefixes().map((prefix) => prefix.split(",")[1])).toEqual([...XPOS_HEADINGS]);
    // Blind, the repair still writes the mark; that is why the predicate is
    // needed rather than a change to what 記号's commonest tag is.
    expect(withPrefix(token().xpos, "s,記号")).toBe("s,記号,句点,*");
    expect(uposForXpos("s,記号,句点,*")).toBe("PUNCT");
    expect(withPrefix(token().xpos, "s,記号", (x) => uposForXpos(x) !== "PUNCT")).toBe("s,記号,一般,*");
    // 文字 is not offered either, for the plainer reason that the treebank
    // does not have it — see the fallback tests below, where a token that has
    // it gets it back.
    expect(prefixes()).not.toContain("v,文字");
  });

  it("keeps 記号 for a token that already is one, and its 一般 with it", () => {
    // The cost of the rule above, and its limit. `s,記号,一般,*` derives to
    // `SYM` — a symbol is not a mark, and such a token resolves like any other
    // — so a token that arrives tagged that way keeps its 品詞 entry, and its
    // domain menu holds the one domain the hiding leaves. What no reader can
    // do is get *to* 記号 from anything else; making that possible is a change
    // to `withPrefix` in xpos.ts (preferring the commonest editable tag),
    // not to this file.
    const symbol = { xpos: "s,記号,一般,*" };
    expect(prefixes(symbol)).toContain("s,記号");
    expect(withPrefix(symbol.xpos, "s,記号")).toBe("s,記号,一般,*");
    expect(domains(symbol)).toEqual(["一般"]);
    expect(uposForXpos("s,記号,一般,*")).toBe("SYM");
    expect(uposJa("SYM")).toBe("記号");
  });

  it("offers one 品詞's domains, and one domain's senses, and nothing wider", () => {
    // The point of the split, stated as a property. A reader choosing what
    // kind of noun a noun is is offered 名詞's fourteen domains rather than the
    // 116 tags the flat menu had, and then that domain's senses — seven at the
    // most, under 名詞・人.
    expect(domains({ xpos: "n,名詞,人,役割" })).toEqual(domainsUnder("n,名詞"));
    expect(domains({ xpos: "n,名詞,人,役割" })).toHaveLength(14);
    expect(senses({ xpos: "n,名詞,人,役割" })).toEqual(sensesUnder("n,名詞", "人"));
    expect(senses({ xpos: "n,名詞,人,役割" })).toHaveLength(7);
    // The longest of each kind, which is what the menus have to fit: 名詞 has
    // the most domains and 動詞・行為 the most senses.
    expect(Math.max(...xposPrefixes().map((p) => domainsUnder(p).length))).toBe(14);
    expect(senses({ xpos: "v,動詞,行為,動作" })).toHaveLength(14);
    // No menu ever reaches outside its own parent.
    for (const prefix of prefixes()) {
      for (const domain of domains(under(prefix))) {
        expect(domainsUnder(prefix), `${prefix} ${domain}`).toContain(domain);
      }
    }
  });

  it("covers the whole editable inventory between them, with nothing left over", () => {
    // Nothing was dropped by the split, only divided — checked by walking all
    // three menus from every 品詞 and collecting what they can reach. All 116
    // of the editable tags, which is the last of three gaps closing.
    //
    // The three, in the order they closed:
    //
    //   `s,記号,句点,*` and its four fellow marks. Never reachable and never
    //       meant to be: `UNEDITABLE_UPOS` hides anything deriving PUNCT,
    //       since a cell that stops resolving is a one-way edit.
    //   `s,記号,一般,*`  a symbol, editable, and unreachable from anything but
    //       a token already wearing it, because picking 記号 first had to
    //       write its commonest tag — a full stop. Closed by giving the same
    //       policy to the repair as to the rows: `withPrefix` takes an
    //       `accept` predicate now and 記号 lands on 一般.
    //   `n,名詞,思考,*`  the one tag in the inventory whose sense is `*` under
    //       a domain that *also* has a real sense (名詞・思考・思考, 862
    //       occurrences against this one's 6). Its own token showed no sense
    //       chip and so opened no sense menu, and no other token could land on
    //       it — `withDomain` takes 思考's commonest sense, which is the real
    //       one. **This is the one this round closes**, and it is closed at
    //       the menu and not at the chip. The reader asked for "no sense" as a
    //       choice; the sense menu offers `*` now, written 「なし」
    //       (`fieldLabel`), so a 名詞・思考 token can be told that its sense is
    //       none. The chip for an empty field is still not drawn, which is
    //       what makes the tag *look* right after the pick: three pills before
    //       it and two after, the row itself saying that the tag records
    //       nothing there. What the reader loses by that is the way back
    //       through the sense menu — see the last case in this describe, where
    //       the route back through the domain chip is walked.
    //
    // So the count moves 115 → 116 and the filter loses its exception. What
    // remains excluded is exactly what a reader must never be able to write.
    expect(XPOS_INVENTORY).toHaveLength(121);
    expect(reachable()).toHaveLength(116);
    expect([...reachable()].sort()).toEqual(
      XPOS_INVENTORY.filter((xpos) => !UNEDITABLE_XPOS.includes(xpos)).sort(),
    );
    // And the tag itself, by the route a reader actually takes: open the sense
    // menu on a 名詞・思考 token and pick the empty row.
    const thought = { xpos: "n,名詞,思考,思考" };
    expect(senses(thought)).toEqual(["思考", "*"]);
    expect(withSense(thought.xpos, "*")).toBe("n,名詞,思考,*");
    // The 思考 case is one of a kind, which is what made it a note rather
    // than a design problem: no other domain mixes a `*` sense with a real one.
    // It is still one of a kind, and it is no longer a note about a gap.
    const mixed = xposPrefixes().flatMap((prefix) =>
      domainsUnder(prefix)
        .filter((domain) => domain !== "*")
        .filter((domain) => {
          const under = sensesUnder(prefix, domain);
          return under.includes("*") && under.length > 1;
        })
        .map((domain) => `${prefix},${domain}`),
    );
    expect(mixed).toEqual(["n,名詞,思考"]);
  });

  it("hides exactly the rows that derive to an uneditable UPOS", () => {
    // Stated as the property rather than as the list, which is what the source
    // actually does: a row goes if what picking it would *write* is
    // uneditable. The list above is then a second, independent statement of
    // the same thing, and the two are checked against each other here.
    const derivesToPunct = XPOS_INVENTORY.filter((xpos) =>
      UNEDITABLE_UPOS.includes(uposForXpos(xpos) ?? ""),
    );
    expect([...derivesToPunct].sort()).toEqual([...UNEDITABLE_XPOS].sort());
    for (const xpos of UNEDITABLE_XPOS) expect(reachable(), xpos).not.toContain(xpos);
    // And through the domain menu specifically, which is where 記号's four
    // mark domains are filtered: only 一般 survives for an ordinary token, and
    // a token that *is* a mark's tag can still see its own.
    expect(domains({ xpos: "s,記号,句点,*" })).toEqual(["一般", "句点"]);
    expect(domains({ xpos: "v,動詞,行為,動作" })).not.toContain("句点");
  });

  it("offers `*`, which is a value a reader can now mean, written 「なし」", () => {
    // The treebank writes `*` for "the scheme records nothing at this level",
    // and `domainsUnder`/`sensesUnder` list it because a round trip needs it.
    // The menus used to strip it, on the argument that the chip for such a
    // level was not drawn, so the menu could not be opened, and a `*` row
    // would be offering a reader the chance to say nothing.
    //
    // The premise held of the token's *own* empty field and was read as
    // holding of everyone's. A token whose sense is real draws a sense chip
    // and opens a sense menu perfectly well; what it could not do there was
    // say that the sense is none. So the row is offered at that one level,
    // written 「なし」 (`fieldLabel`), and the chip is left exactly as it was:
    // a menu row says what a reader may choose, a pill says what the tag
    // records, and an empty pill would say that the app went looking for a
    // sense and came back with a placeholder.
    expect(domainsUnder("p,接尾辞")).toContain("*");
    expect(sensesUnder("p,助詞", "句末")).toEqual(["*"]);
    expect(domains({ xpos: "p,接尾辞,*,*" })).toEqual([]);
    expect(senses({ xpos: "p,助詞,句末,*" })).toEqual(["*"]);
    // What a `*` row is drawn as, which is the other half of offering it. The
    // stored value stays `*` — that is what a round trip needs and what the
    // shading asks about — and only the label is Japanese.
    expect(fieldLabel("*")).toBe(EMPTY_FIELD_LABEL);
    expect(fieldLabel("思考")).toBe("思考");

    // **The domain menu keeps the old filter**, and that is not an
    // inconsistency — it is that the row buys nothing there. `*` is a domain
    // of only three 品詞: under 接尾辞 and 感嘆詞 it is the only one, so a
    // token there draws no domain chip and has no menu to put the row in;
    // under 記号 it would write `s,記号,*,*`, which derives PUNCT and goes by
    // the uneditable rule. A row that no menu can show and no menu may offer
    // is not a row.
    const withStar = xposPrefixes().filter((prefix) => domainsUnder(prefix).includes("*"));
    expect(withStar).toEqual(["s,記号", "p,接尾辞", "p,感嘆詞"]);
    expect(domains({ xpos: "s,記号,一般,*" })).not.toContain("*");
    expect(uposForXpos("s,記号,*,*")).toBe("PUNCT");
    for (const prefix of xposPrefixes()) {
      expect(domainMenuValues(token({ xpos: xposesUnder(prefix)[0] })), prefix).not.toContain("*");
    }

    // At the sense level it changes exactly one menu a reader can open on
    // anything else — 名詞・思考 — and that is the whole point of it.
    expect(senses({ xpos: "n,名詞,思考,思考" })).toEqual(["思考", "*"]);
    // The rest are menus of one, on tokens that draw no sense chip and so
    // never open them. This function answers about the field rather than about
    // the chip, which is why they are not filtered here.
    expect(posChipParts(token({ xpos: "p,助詞,句末,*" })).sense).toBeUndefined();

    // **And a token at `*` is not stranded**, which is the objection a missing
    // chip invites. Its domain chip is still there, and the way back is
    // through it: pick another domain, then 思考 again, and `withDomain` takes
    // that domain's commonest sense — the real one. What does *not* work is
    // picking 思考 without leaving it first, `*` being a member of 思考's own
    // sense list and so kept by the repair.
    expect(withDomain("n,名詞,思考,*", "思考")).toBe("n,名詞,思考,*");
    expect(withDomain(withDomain("n,名詞,思考,*", "人"), "思考")).toBe("n,名詞,思考,思考");
  });

  it("keeps each menu in the corpus's order, and re-sorts none of them", () => {
    // The order is `xposPrefixes`/`domainsUnder`/`sensesUnder`'s, less
    // whatever the filtering took out, and nothing in this app re-sorts it —
    // which is what lets the shading and the position say the same thing (see
    // `tests/menuShading.test.ts`).
    for (const prefix of xposPrefixes()) {
      expect(domains(under(prefix)), prefix).toEqual(
        domainsUnder(prefix).filter(
          (domain) =>
            domain !== "*" &&
            !UNEDITABLE_UPOS.includes(uposForXpos(withDomain(under(prefix).xpos, domain)) ?? ""),
        ),
      );
    }
  });

  it("never offers an empty menu from a chip that can be right-clicked", () => {
    // A menu is opened from a chip and a chip is drawn only where the token
    // records that level, so the two empty cases are unreachable rather than
    // broken: a token with no tag has no domain chip, and one whose sense is
    // `*` has no sense chip. Checked as the *pairing* — over the whole
    // inventory, a chip and an empty menu never occur together — rather than
    // on the two examples, since it is the pairing that would break.
    for (const xpos of XPOS_INVENTORY) {
      const parts = posChipParts(token({ xpos }));
      if (parts.domain !== undefined) expect(domains({ xpos }).length, xpos).toBeGreaterThan(0);
      if (parts.sense !== undefined) expect(senses({ xpos }).length, xpos).toBeGreaterThan(0);
    }
    for (const prefix of prefixes()) {
      // Only where there is a chip to open it from: 接尾辞 and 感嘆詞 record
      // no semantics at all, so they draw one chip and have no lower menus.
      if (posChipParts(token(under(prefix))).domain !== undefined) {
        expect(domains(under(prefix)).length, prefix).toBeGreaterThan(0);
      }
      for (const domain of domains(under(prefix))) {
        const tagged = { xpos: withDomain(under(prefix).xpos, domain) };
        const parts = posChipParts(token(tagged));
        if (parts.sense !== undefined) {
          expect(senses(tagged).length, tagged.xpos).toBeGreaterThan(0);
        }
      }
    }
    for (const nothing of ["", "_", "v,動詞"]) {
      expect(domains({ xpos: nothing }), nothing).toEqual([]);
      expect(senses({ xpos: nothing }), nothing).toEqual([]);
      expect(posChipParts(token({ xpos: nothing })).domain, nothing).toBeUndefined();
    }
  });

  it("labels every row of all three menus", () => {
    // Each menu draws its field through `fieldLabel`, so a value that was not
    // Japanese would appear as itself in a column of Japanese. `*` is the one
    // such value in the tagset and it is offered now rather than hidden — so
    // the check is on the *label*, which is where the ASCII has to stop, and
    // not on the value, which is what gets stored.
    const ascii = /^[^\x00-\x7f]+$/;
    for (const prefix of prefixes()) {
      expect(prefix.split(",")[1], prefix).toMatch(ascii);
      for (const domain of domains(under(prefix))) {
        expect(fieldLabel(domain), prefix).toMatch(ascii);
        for (const sense of senses({ xpos: withDomain(under(prefix).xpos, domain) })) {
          expect(fieldLabel(sense), `${prefix} ${domain}`).toMatch(ascii);
        }
      }
    }
    // And the two 品詞 whose only domain is the empty one, which the walk above
    // reaches only through `under()` and so would not otherwise label.
    for (const xpos of ["p,接尾辞,*,*", "p,感嘆詞,*,*"]) {
      for (const domain of domains({ xpos })) expect(fieldLabel(domain), xpos).toMatch(ascii);
      for (const sense of senses({ xpos })) expect(fieldLabel(sense), xpos).toMatch(ascii);
    }
  });
});

describe("the relation menu is untouched", () => {
  it("files exactly the 34 relations the parser can emit", () => {
    expect([...DEPREL_INVENTORY].sort()).toEqual([...PARSER_DEPRELS].sort());
  });

  it("offers the 34 less the uneditable relation, and goes on naming it", () => {
    expect([...offeredRels()].sort()).toEqual(
      PARSER_DEPRELS.filter((r) => !UNEDITABLE_DEPRELS.includes(r)).sort(),
    );
    for (const rel of UNEDITABLE_DEPRELS) expect(offeredRels(), rel).not.toContain(rel);
    expect(deprelJa("punct")).toBe("句読点");
  });
});

describe("a token wearing a value the menus do not offer keeps it", () => {
  it("shows that value in its own menu, and only for that token", () => {
    // The upload path, and now the tagger's own composition as well: a
    // CoNLL-U file can carry any four fields at all, and the tagger picks each
    // field separately so it can write a combination the treebank never has.
    // Hiding it from that token's own menu would leave the chip naming a
    // category the menu did not contain, with the first edit discarding it
    // silently. The rule holds at all three levels, so it is checked at all
    // three.
    expect(prefixes({ xpos: "v,文字,行為,動作" })).toContain("v,文字");
    expect(prefixes()).not.toContain("v,文字");
    expect(domains({ xpos: "n,名詞,存在,存在" })).toContain("存在");
    expect(domains({ xpos: "n,名詞,人,役割" })).not.toContain("存在");
    expect(senses({ xpos: "n,名詞,人,動作" })).toContain("動作");
    expect(senses({ xpos: "n,名詞,人,役割" })).not.toContain("動作");
    // Including a value the menu hides on purpose: a token that is a mark's
    // tag can still see the domain it has.
    expect(domains({ xpos: "s,記号,句点,*" })).toContain("句点");
  });

  it("appends it rather than sorting it in, the order being a frequency one", () => {
    // Where it goes, and why there. Every one of these menus is in corpus
    // order, and an unattested value has no frequency to be ordered by —
    // putting it among the attested rows would be claiming one. Last is the
    // one position that claims nothing.
    expect(prefixes({ xpos: "v,文字,行為,動作" }).at(-1)).toBe("v,文字");
    expect(prefixes({ xpos: "v,文字,行為,動作" }).slice(0, -1)).toEqual(prefixes());
    const invented = domains({ xpos: "n,名詞,存在,存在" });
    expect(invented.at(-1)).toBe("存在");
    expect(invented.slice(0, -1)).toEqual(domains({ xpos: "n,名詞,人,役割" }));
  });

  it("adds nothing at all for a token with no tag", () => {
    // `""` is what the CoNLL-U importer writes for a `_` in the XPOS column,
    // and it is not a category — a twelfth 品詞 entry named by the empty string
    // is what a truthiness test in the source would have produced. Such a
    // token gets the plain list, with nothing marked as current, which is
    // correct: its chip is showing a UPOS, and none of the entries is that.
    for (const nothing of ["", "_", "v,動詞"]) {
      expect(prefixes({ xpos: nothing }), nothing).toEqual(prefixes());
      expect(domains({ xpos: nothing }), nothing).toEqual([]);
      expect(senses({ xpos: nothing }), nothing).toEqual([]);
    }
  });

  it("does the same for a relation the menu does not offer", () => {
    // The deprel menu needed the fallback too, and did not have one until
    // `punct` became the first relation ever hidden from it. A CoNLL-U file
    // can give an ordinary character the `punct` relation, and resolution
    // keys on the *tag*, so such a token draws an arrow and opens a menu.
    expect(offeredRels()).not.toContain("punct");
    const withPunct = deprelMenuGroups("punct").flatMap(([, rows]) =>
      rows.flatMap((r) => r.segments.filter((sg) => sg.kind === "relation").map((sg) => sg.value)),
    );
    expect(withPunct).toContain("punct");
    expect([...withPunct].sort()).toEqual([...PARSER_DEPRELS].sort());
    // and in its own group, not appended
    const group = deprelMenuGroups("punct").find(([, rows]) => rows.some((r) => r.base === "punct"));
    expect(group?.[0]).toBe("談話・その他");
  });

  it("never empties a relation group either", () => {
    for (const current of ["", "punct", "mod", "ROOT"]) {
      for (const [heading, rows] of deprelMenuGroups(current)) {
        expect(rows.length, `${current} / ${heading}`).toBeGreaterThan(0);
      }
    }
  });
});

/** **What each of the three picks writes.**
 *
 * The repair itself is `withPrefix`/`withDomain`/`withSense` in xpos.ts and is
 * tested there. What is tested here is what this app does with them: that each
 * menu's rows are wired to the right one, that a pick lands on a tag the other
 * two chips can then show, and that nothing else about the token moves. */
describe("what a pick writes", () => {
  /** The whole of a category edit, copied from `openRetagMenu` rather than
   * imported because it is a closure that needs a document — and the point of
   * these is that this is *all* it is. */
  const pick = (t: Token, xpos: string): Token => {
    const upos = uposForXpos(xpos, t.morph);
    return { ...t, xpos, ...(upos === undefined ? {} : { pos: upos }) };
  };

  it("keeps the semantics that survive a change of 品詞", () => {
    // The reason the repair is a repair and not a reset. Several pairs are
    // shared across prefixes — 描写・形質 and 描写・態度 sit under both 名詞 and
    // 動詞, which is the treebank saying that a property word can be nominal or
    // verbal and is the same property word either way. A reader correcting 高
    // from a noun to a verb is saying something about its syntax and nothing
    // about its sense, and both lower chips should read the same afterwards.
    const noun = token({ xpos: "n,名詞,描写,形質", pos: "NOUN" });
    const asVerb = pick(noun, withPrefix(noun.xpos, "v,動詞"));
    expect(asVerb.xpos).toBe("v,動詞,描写,形質");
    expect(posChipParts(asVerb)).toEqual({ word: "動詞", domain: "描写", sense: "形質" });
    expect(posChipParts(noun).domain).toBe(posChipParts(asVerb).domain);
    expect(posChipParts(noun).sense).toBe(posChipParts(asVerb).sense);
  });

  it("falls back only where the old value has no meaning under the new parent", () => {
    // And where it does fall back, it falls to the commonest — which is the
    // corpus's modal answer for that parent and the row the menu shows first,
    // so the guess is visible on the chip the moment the menu closes and is
    // one click from being corrected on the chip beside it.
    expect(withPrefix("n,名詞,人,役割", "v,動詞")).toBe("v,動詞,行為,動作");
    expect(withDomain("v,動詞,行為,動作", "描写")).toBe("v,動詞,描写,形質");
    expect(xposesUnder("v,動詞")[0]).toBe("v,動詞,行為,動作");
    expect(sensesUnder("v,動詞", "描写")[0]).toBe("形質");
    // A sense pick repairs nothing, there being nothing below it.
    expect(withSense("v,動詞,行為,動作", "伝達")).toBe("v,動詞,行為,伝達");
  });

  it("always lands on a tag the three chips can show", () => {
    // The property that makes the menus composable: after any pick from any
    // menu, the chip whose menu it was reads what was picked, and the other
    // two read something the treebank writes. Walked over every entry of every
    // menu from every 品詞, because the repair is what could get this wrong.
    for (const prefix of prefixes()) {
      const start = under(prefix).xpos!;
      for (const other of prefixes()) {
        const next = withPrefix(start, other);
        expect(XPOS_INVENTORY, `${start} -> ${other}`).toContain(next);
        expect(posChipParts({ pos: "", xpos: next }).word).toBe(other.split(",")[1]);
      }
      for (const domain of domains(under(prefix))) {
        const next = withDomain(start, domain);
        expect(XPOS_INVENTORY, `${start} -> ${domain}`).toContain(next);
        expect(posChipParts({ pos: "", xpos: next }).domain ?? "*").toBe(domain);
        for (const sense of senses({ xpos: next })) {
          const deeper = withSense(next, sense);
          expect(XPOS_INVENTORY, `${next} -> ${sense}`).toContain(deeper);
          // `?? "*"` covers the one sense pick that leaves no chip behind: the
          // empty row this menu now offers. Picking it is a real edit — it is
          // how `n,名詞,思考,*` is reached — and what it writes is a tag whose
          // sense field the chips do not draw.
          expect(posChipParts({ pos: "", xpos: deeper }).sense ?? "*").toBe(sense);
        }
      }
    }
  });

  it("never writes an uneditable UPOS from a row a menu offers", () => {
    // The hiding, checked through the picks rather than through the lists.
    // The token's own value is the one exception and it is not a row the menu
    // chose: it is shown so the reader can see what the chip is saying, and
    // picking it writes the tag the token already has (below).
    for (const prefix of prefixes()) {
      const start = under(prefix).xpos!;
      for (const other of prefixes()) {
        const landed = withPrefix(start, other, (x) => editableTag(x, { morph: undefined }));
        expect(uposForXpos(landed), `${start} -> ${other}`).not.toBe("PUNCT");
      }
      for (const domain of domains(under(prefix))) {
        expect(uposForXpos(withDomain(start, domain)), `${start} -> ${domain}`).not.toBe("PUNCT");
      }
    }
  });

  it("writes the token's own tag back when its own value is picked", () => {
    // The degenerate entry, and the one place a pick can write an uneditable
    // tag — which it can only do by writing the tag the token already has. A
    // token whose xpos says 記号・句点 but whose UPOS does not say PUNCT (only
    // an upload can be in that state; the parser's own trees agree with
    // themselves) can be inspected, and picking 句点 in its own domain menu
    // writes 記号・句点 back and lets the derivation say PUNCT — after which
    // the token stops resolving.
    //
    // It is left alone rather than special-cased. A menu's guarantee is about
    // the rows it *offers*, and the token's own value is not one of those.
    // Refusing it would mean an entry marked as current that cannot be chosen,
    // which is a worse thing to explain than an edit that writes what the
    // token already said.
    expect(withDomain("s,記号,句点,*", "句点")).toBe("s,記号,句点,*");
    for (const xpos of ["n,名詞,人,役割", "v,動詞,描写,形質", "p,助詞,句末,*"]) {
      const parts = xpos.split(",");
      expect(withPrefix(xpos, `${parts[0]},${parts[1]}`), xpos).toBe(xpos);
      expect(withDomain(xpos, parts[2]), xpos).toBe(xpos);
      expect(withSense(xpos, parts[3]), xpos).toBe(xpos);
    }
  });
});

describe("the adjective, which is a derived category now", () => {
  /** What the menu's click does, which is the whole of a 品詞 edit: the xpos
   * the reader picked, and the UPOS that follows from it and from the features
   * the token already carries. Copied from `openRetagMenu` rather than
   * imported because it is a closure that needs a document — and the point of
   * these is that this is *all* it is. */
  const pick = (t: Token, choice: string): Token => {
    const upos = uposForXpos(choice, t.morph);
    return { ...t, xpos: choice, ...(upos === undefined ? {} : { pos: upos }) };
  };

  it("is not a tag anyone picks, it is what 描写 amounts to", () => {
    // The history this file was opened for, in its third form. 0.3.1 had no
    // ADJ at all and this app synthesised 形容詞 out of `VERB` + `Degree=Pos`;
    // 0.3.2 emitted the tag and the synthesis was deleted; and now the tag is
    // not on offer either, because the menus offer what the treebank writes
    // and the treebank does not write UPOS. What a reader picks is 動詞 on one
    // chip, 描写 on the next and 形質 on the third — a verb of description,
    // which is what a Classical Chinese property word is — and ADJ is what
    // that derives to.
    expect(XPOS_INVENTORY).toContain("v,動詞,描写,形質");
    expect(posChipParts({ pos: "ADJ", xpos: "v,動詞,描写,形質" })).toEqual({
      word: "動詞",
      domain: "描写",
      sense: "形質",
    });
    expect(uposForXpos("v,動詞,描写,形質")).toBe("ADJ");
    expect(uposJa("ADJ")).toBe("形容詞");
    // All four 描写 rows are adjectival, which is what makes this a category
    // rather than a lexical accident.
    const descriptive = XPOS_INVENTORY.filter((xpos) => xpos.startsWith("v,動詞,描写,"));
    expect(descriptive).toHaveLength(4);
    for (const xpos of descriptive) expect(uposForXpos(xpos), xpos).toBe("ADJ");
  });

  it("becomes an adverb on a token used adverbially, without the reader saying so", () => {
    // The case the task of deriving UPOS was really about. A 描写 verb with
    // `VerbForm=Conv` is a property word used adverbially — 節用 in the
    // Analects, 節 tagged ADV — and the derivation says ADV for it. So a
    // reader picking 描写 on such a token is *not* overruling the
    // features: they are saying what the word is, and how it is being used is
    // still what the morph says.
    const conv = token({ xpos: "v,動詞,行為,動作", pos: "ADV", morph: "Degree=Pos|VerbForm=Conv" });
    const after = pick(conv, "v,動詞,描写,形質");
    expect(after.xpos).toBe("v,動詞,描写,形質");
    expect(after.pos).toBe("ADV");
    expect(after.morph).toBe("Degree=Pos|VerbForm=Conv");
    // And the same row on a token with no such feature is the adjective.
    expect(pick(token({ morph: undefined }), "v,動詞,描写,形質").pos).toBe("ADJ");
  });

  it("is the copula that AUX comes from, and only there", () => {
    // The other derivation that reads a feature: `VerbType=Cop` on
    // 動詞〖存在・存在〗 — the copular 爲 this app argues about at length in
    // verbLexicon.ts. Nothing else in the inventory produces an AUX except the
    // four 助動詞 rows, which are auxiliaries outright.
    expect(uposForXpos("v,動詞,存在,存在", "VerbType=Cop")).toBe("AUX");
    expect(uposForXpos("v,動詞,存在,存在")).toBe("VERB");
    const auxes = XPOS_INVENTORY.filter((xpos) =>
      ["", "VerbType=Cop"].some((morph) => uposForXpos(xpos, morph) === "AUX"),
    );
    expect([...auxes].sort()).toEqual(
      ["v,動詞,存在,存在", "v,助動詞,受動,*", "v,助動詞,可能,*", "v,助動詞,必要,*", "v,助動詞,願望,*"].sort(),
    );
  });
});

describe("a 品詞 edit writes the tag, derives the UPOS, and touches nothing else", () => {
  const pick = (t: Token, choice: string): Token => {
    const upos = uposForXpos(choice, t.morph);
    return { ...t, xpos: choice, ...(upos === undefined ? {} : { pos: upos }) };
  };

  /** Feature bundles as the worker writes them — spaCy's `str(token.morph)`,
   * which excludes `POS=` and is sorted. Drawn from the shapes 0.3.2's own
   * morphologiser labels take, plus the empty case and the legacy `VERB` +
   * `Degree=Pos` that 0.3.1 produced and 0.3.2 never will. The two the
   * derivation actually reads — `VerbForm` and `VerbType` — are in here in
   * every combination the treebank attests. */
  const MORPHS = [
    undefined,
    "",
    "VerbForm=Part",
    "VerbForm=Conv",
    "VerbType=Cop",
    "Degree=Pos",
    "Degree=Pos|VerbForm=Conv",
    "Degree=Equ|VerbForm=Part",
    "Shared=Yes|VerbForm=Part",
    "ExtPos=VERB",
  ];

  it("leaves the morph untouched, whatever is picked", () => {
    // The morph says how the word is being used and the xpos says what it is;
    // the reader is editing the second. Stated over every row and every bundle
    // rather than on an example, because the temptation to "fix up" the
    // features to agree with the new tag is exactly what this forbids.
    for (const morph of MORPHS) {
      for (const choice of XPOS_INVENTORY) {
        const after = pick(token({ morph }), choice);
        expect(after.morph, `${morph} -> ${choice}`).toBe(morph);
        expect(after.xpos, `${morph} -> ${choice}`).toBe(choice);
      }
    }
  });

  it("sets the UPOS to what the tag and those features amount to", () => {
    for (const morph of MORPHS) {
      for (const choice of XPOS_INVENTORY) {
        expect(pick(token({ morph }), choice).pos, `${morph} -> ${choice}`).toBe(
          uposForXpos(choice, morph),
        );
        // Never undefined for a row the menu offers: every attested tag has a
        // derivation, and a feature bundle the treebank never wrote falls back
        // to the featureless entry rather than to nothing.
        expect(uposForXpos(choice, morph), `${morph} -> ${choice}`).toBeDefined();
      }
    }
  });

  it("leaves the UPOS exactly as it was where nothing can be derived", () => {
    // The one case that must not write a guess. An uploaded tree can carry a
    // tag outside the derivation table — its own scheme, or a composition the
    // treebank has never attested — and this app has no opinion to record
    // about it. A stale UPOS is recoverable by looking at the tree; a
    // fabricated one is not distinguishable from a real one afterwards.
    for (const unattested of ["n,名詞,思考,存在", "v,文字,行為,動作"]) {
      expect(uposForXpos(unattested), unattested).toBeUndefined();
      const after = pick(token({ pos: "NOUN", xpos: "n,名詞,人,役割" }), unattested);
      expect(after.xpos, unattested).toBe(unattested);
      expect(after.pos, unattested).toBe("NOUN");
    }
  });

  it("has no trapdoor: every reachable tag can be reached from every other", () => {
    // What makes the edit reversible in one step, or in two — which is the
    // change the split made to this property and is worth being exact about.
    // The flat menu put every tag one click away; the three menus put a tag
    // under a different 品詞 one click away *at each level it differs*, so
    // 名詞・人・役割 to 動詞・描写・形質 is three picks and not one. What is
    // preserved is that nothing is unreachable and nothing is one-way.
    for (const from of ["n,名詞,人,役割", "v,動詞,行為,動作", "p,助詞,句末,*"]) {
      for (const to of reachable()) {
        const walked = pick(token({ xpos: from, morph: "VerbForm=Conv" }), to);
        expect(walked.xpos, `${from} -> ${to}`).toBe(to);
        expect(walked.morph, `${from} -> ${to}`).toBe("VerbForm=Conv");
        const back = pick(walked, from);
        expect(back.xpos, `${to} -> ${from}`).toBe(from);
      }
    }
  });

  it("can never write an uneditable UPOS from a row a menu offers", () => {
    // The hiding, checked where it matters rather than where it is written:
    // whatever the token's features, no reachable tag turns it into something
    // that stops resolving. This is the property `UNEDITABLE_UPOS` exists for,
    // and the derived filtering is what makes it hold for every feature bundle
    // rather than for the featureless one the filter is asked with.
    for (const morph of MORPHS) {
      for (const choice of reachable()) {
        expect(uposForXpos(choice, morph), `${morph} -> ${choice}`).not.toBe("PUNCT");
      }
    }
  });
});
