import type { ConjClass } from "./classicalConjugation.ts";
import derivedData from "./verb-lexicon-index.json";

/** Per-lemma classical-conjugation data, keyed by the bare kanji (matching
 * `Token.lemma`). The overwhelming majority of this table (`derivedData`,
 * below) is generated by `scripts/build-verb-lexicon.mjs` directly from
 * Wiktionary's own classical-conjugation tables — not hand-typed — by
 * matching each word's six attested classical base forms against
 * `classicalConjugation.ts`'s own paradigm shapes. Re-run that script
 * (see its own doc for how) to pick up new words or a fresher Wiktionary
 * dump; nothing here should be hand-added for a word the script can
 * already resolve.
 *
 * `okuriganaPrefix` covers words whose conventional okurigana boundary
 * starts earlier than the conjugation class's own suffix — e.g. 説ばし
 * (よろこばし) has kanji 説 covering only "よろこ", with "ば" as a fixed
 * prefix before the しく-adjective suffix proper (説+ば+しから = 説ばしから) —
 * the build script derives this the same mechanical way, by finding the
 * common leading substring that must be stripped before the remaining six
 * forms match a known paradigm.
 *
 * `fixedReading`, where present, bypasses conjugation entirely for a
 * lexicalized reading that doesn't vary with syntactic context (e.g. 曰
 * introducing reported speech is conventionally read 曰はく regardless of
 * what follows it — a nominalized -aku form, not a plain conjugated verb).
 *
 * `reading` is the word's own kanji-covered furigana reading, used only by
 * `KundokuView.ts` (kakikudashi never shows a reading for a kanji-retained
 * word). This is *not* re-derivable from `kanjidicLookup.ts`'s generic
 * kun'yomi lookup, which was tried and reverted: kanjidic only knows a
 * character's *readings*, not which one belongs to the specific verb/
 * adjective sense being conjugated here (中's kun'yomi list is
 * ["なか","うち","あた.る"] — a bare character lookup has no signal that a
 * verb use of 中 wants the third one, not the first, giving なかる instead
 * of あたる). The build script instead reads this off the very same
 * matched conjugation block that supplied `conjClass` — already
 * sense-disambiguated data, not a second guess at the same fact. It's
 * still run through the general historical-kana correction at render time
 * (`historicalKana.ts`, in `KundokuView.ts`) rather than baked in here, so
 * a fresher Wiktionary dump keeps benefiting from that index. */
export interface LexiconEntry {
  conjClass?: ConjClass;
  okuriganaPrefix?: string;
  fixedReading?: string;
  reading?: string;
}

/** The residual: kanbun content words this app needs whose classical sense
 * Wiktionary's Japanese data can't supply the build script an answer for —
 * each commented with *why*, not just *what*, so a future Wiktionary dump
 * that starts covering one can have its entry deleted rather than
 * silently kept stale. Never overrides a lemma `derivedData` already
 * resolves correctly (see the merge below) — this is a set of gaps to
 * fill, not a correction layer sitting in front of the general mechanism
 * (that pattern was tried and reverted for historical-kana readings; the
 * lesson applies here too). */
const RESIDUAL: Record<string, LexiconEntry> = {
  // 曰: two distinct uses, both needing a hand-supplied answer since
  // Wiktionary has no verb entry for 曰 at all (regardless of sense).
  // Introducing reported speech (子曰：「...」), 曰はく is a fixed -aku
  // nominalization, not a conjugating verb — `fixedReading` bypasses
  // conjugation entirely for that case (see `isNamingUse` in
  // conjugationContext.ts for how the dispatch tells the two apart). Used
  // instead as a plain naming verb (名曰軒轅, "[his] name was Xuanyuan" —
  // not a quotation), it conjugates normally as いふ/いう, the same 四段ハ行
  // class as 言ふ/謂ふ — `conjClass` covers that case. kanjidic's own
  // いわ.く is the *modern* spelling (わ, not は) and splits at the wrong
  // boundary for the fixedReading case besides, so `reading` is supplied
  // directly rather than deferring to it either way.
  曰: { fixedReading: "はく", conjClass: "yodan-ha", reading: "い" },

  // よろこばし ("pleased") — Wiktionary's 悦/説/悦ばしい pages are all
  // soft-redirects with no conjugation data, and 説 itself only has an
  // entry for its unrelated と.く ("to explain") sense.
  說: { conjClass: "shiku-keiyoushi", okuriganaPrefix: "ば", reading: "よろこ" },
  説: { conjClass: "shiku-keiyoushi", okuriganaPrefix: "ば", reading: "よろこ" },
  悦: { conjClass: "shiku-keiyoushi", okuriganaPrefix: "ば", reading: "よろこ" },

  // 慍む (上二段マ行, "to resent") — no modern reflex in Wiktionary at all;
  // this sense didn't survive into contemporary Japanese vocabulary.
  慍: { conjClass: "kami-nidan-ma", reading: "うら" },

  // 謂ふ ("to call/say X") — "謂う" is a soft-redirect with no data; same
  // は行四段 row as 言ふ, which does have a full attested table.
  謂: { conjClass: "yodan-ha", reading: "い" },

  // 為す ("to do/make") — "為す"/"爲す" are soft-redirects; さ変 is the
  // well-known irregular class for this word regardless.
  爲: { conjClass: "sa-hen", reading: "な" },
  為: { conjClass: "sa-hen", reading: "な" },

  // 成る ("to become") — a genuine homograph the build script can't resolve
  // on its own: 成/為 are *both* attested kanji spellings of two different
  // kana-headword verbs, なる ("to become", 四段ラ行) and なす ("to do/make",
  // 四段サ行 — な+す, unrelated to 為す above despite the same kanji), each
  // only reachable via its kana entry's own "kanji"-tagged alternate forms,
  // not a direct kanji-headword page of its own. Whichever entry the build
  // script happens to reach first for a given kanji wins by construction
  // (see its own doc) — for 成 that was なす, giving the wrong sense for
  // 成而聰明 ("becoming wise", 成る, not "making [something]"). 為 doesn't
  // need its own residual line for this, since it already has the sa-hen
  // one above (為す, not なる, is the standard kundoku sense there).
  成: { conjClass: "yodan-ra", reading: "な" },

  // 来たる ("to arrive from afar") — the build script's own derived answer
  // for 來/来 is also correct 四段ラ行 with the correct full reading きた,
  // but this app's kanbun-kundoku convention shows たる visibly as okurigana
  // (来たる) rather than folding it into the furigana (来る read きたる) the
  // way Wiktionary's own bungo-table forms (來ら/來り, kanji alone covering
  // the whole きた) do — a *typesetting* convention difference, not a
  // conjugation-class disagreement, so only the reading/okurigana split
  // changes here, not the class itself.
  來: { conjClass: "yodan-ra", okuriganaPrefix: "た", reading: "き" },
  来: { conjClass: "yodan-ra", okuriganaPrefix: "た", reading: "き" },

  // 往ぬ ("to go/depart") — soft-redirect, no data; classical grammar has
  // exactly two ナ変 verbs (死ぬ/往ぬ), 死 already resolves via Wiktionary.
  往: { conjClass: "na-hen", reading: "い" },

  // 取る ("to take") — itself a soft-redirect with no data; only its modern
  // compounds (取り戻す etc.) have full entries, none in the plain row.
  取: { conjClass: "yodan-ra", reading: "と" },

  // 少なし ("few") — modern 少ない has no classical table (its "ない" is a
  // separate modern negative-adjective suffix, not this word's own okurigana).
  少: { conjClass: "ku-keiyoushi", reading: "すくな" },

  // 挺く ("to spring back straight") — Wiktionary's only 挺す entry is the
  // unrelated on'yomi sense ていす ("to nominate oneself"), さ変; kanjidic's
  // sole attested kun'yomi for this sense is 抜く-shaped ぬ.く, a documented
  // best-effort guess (see the app's own reading-resolution notes), not a
  // confirmed traditional kundoku for this specific line.
  挺: { conjClass: "yodan-ka", reading: "ぬ" },

  // 博し ("broad, extensive") — no plain adjective entry at all in
  // Wiktionary; only na-adjective compounds (博学/博識/博雅) exist.
  博: { conjClass: "ku-keiyoushi", reading: "ひろ" },

  // 磨く ("to grind/polish", 金就礪則利's 礪) — has no entry at all (derived
  // or otherwise): kanjidic lists it under 磨/研, not this variant kanji, and
  // Wiktionary's own page for this word never lists 礪 among its spellings.
  // 四段カ行, the regular class for a plain -く verb like this.
  礪: { conjClass: "yodan-ka", reading: "みが" },

  // 無し ("there is not") — the derived entry for 無/无 is 為す's homophone
  // なす ("to do/make", a real but unrelated word also spelled 成す/為す),
  // the same cross-entry ambiguity as 成/為/成 above: 無 and 无 are both
  // attested kanji spellings of なす's kana headword too, and that entry
  // wins the extraction script's first-match race. ク活用, not a verb at
  // all — 無き人 (rentai), 無し (shuushi), matching real kanbun convention
  // (overrides.json's own contextPos:["VERB"] "なし" entry for this same
  // character is consequently never reached, since VERB_LEXICON is checked
  // first whenever pos is VERB — this residual entry is what actually fixes
  // it, not that override).
  無: { conjClass: "ku-keiyoushi", reading: "な" },
  无: { conjClass: "ku-keiyoushi", reading: "な" },

  // 戰/戦: three unrelated Japanese verbs share this spelling — たたかふ
  // "to fight" (四段ハ), をののく "to tremble" (四段カ) and そよぐ "to
  // rustle" (四段ガ) — and the build script, which takes the first entry
  // it can classify, lands on をののく. In kanbun the character is the
  // ordinary word for fighting or waging war; the trembling sense is a
  // different word that happens to be written the same way. The same
  // false-positive-on-another-sense case as 説/說 above, not mere
  // uncertainty. The class and reading match 闘/鬪, which the script
  // already resolves correctly for the same meaning.
  戰: { conjClass: "yodan-ha", reading: "たたか" },
  戦: { conjClass: "yodan-ha", reading: "たたか" },
};

const derived = derivedData as Record<string, LexiconEntry>;

// RESIDUAL wins where both exist — every entry in it is there specifically
// because the build script's derived answer for that kanji (説/說's only
// modern entry is 説く "to explain", a same-spelling different-sense
// homograph of the よろこばし this app needs) is for the wrong word, not
// because it's merely uncertain. This is the opposite merge order from
// historical-kana's index (a hand table was tried *in front of* that
// general index and reverted — see readingResolver.ts): there, every
// kanji the general index covered had a genuinely correct answer already;
// here, `derived`'s coverage of these specific kanji is a false positive
// on an unrelated sense, not a lower-confidence version of the right one.
export const VERB_LEXICON: Record<string, LexiconEntry> = { ...derived, ...RESIDUAL };
