import { conjugate, type ConjClass } from "./classicalConjugation.ts";
import derivedData from "./verb-lexicon-index.json";

/** Per-lemma classical-conjugation data, keyed by the bare kanji (matching
 * `Token.lemma`). The overwhelming majority of this table (`derivedData`,
 * below) is generated by `scripts/build-verb-lexicon.mjs` directly from
 * Wiktionary's own classical-conjugation tables — not hand-typed — by
 * matching each word's six attested classical base forms against
 * `classicalConjugation.ts`'s own paradigm shapes. Re-run that script
 * (see its own doc for how) to pick up new words or a fresher Wiktionary
 * dump; nothing here should be hand-added for a word the script can
 * already resolve. That index holds a *list* of senses per kanji —
 * `VERB_LEXICON` is each list's leading one and `LEXICON_SENSES` the whole
 * of it.
 *
 * `okuriganaPrefix` covers words whose conventional okurigana boundary
 * starts earlier than the conjugation class's own suffix — e.g. 説ばし
 * (よろこばし) has kanji 説 covering only "よろこ", with "ば" as a fixed
 * prefix before the しく-adjective suffix proper (説+ば+しから = 説ばしから) —
 * the build script derives this the same mechanical way, by finding the
 * common leading substring that must be stripped before the remaining six
 * forms match a known paradigm.
 *
 * `fixedReading`, where present, bypasses conjugation entirely for a
 * lexicalized reading that doesn't vary with syntactic context (e.g. 曰
 * introducing reported speech is conventionally read 曰はく regardless of
 * what follows it — a nominalized -aku form, not a plain conjugated verb).
 *
 * `reading` is the word's own kanji-covered furigana reading, used only by
 * `KundokuView.ts` (kakikudashi never shows a reading for a kanji-retained
 * word). This is *not* re-derivable from `kanjidicLookup.ts`'s generic
 * kun'yomi lookup, which was tried and reverted: kanjidic only knows a
 * character's *readings*, not which one belongs to the specific verb/
 * adjective sense being conjugated here (中's kun'yomi list is
 * ["なか","うち","あた.る"] — a bare character lookup has no signal that a
 * verb use of 中 wants the third one, not the first, giving なかる instead
 * of あたる). The build script instead reads this off the very same
 * matched conjugation block that supplied `conjClass` — already
 * sense-disambiguated data, not a second guess at the same fact. It's
 * still run through the general historical-kana correction at render time
 * (`historicalKana.ts`, in `KundokuView.ts`) rather than baked in here, so
 * a fresher Wiktionary dump keeps benefiting from that index. */
export interface LexiconEntry {
  conjClass?: ConjClass;
  okuriganaPrefix?: string;
  fixedReading?: string;
  reading?: string;
}

/** The residual: kanbun content words this app needs whose classical sense
 * Wiktionary's Japanese data can't supply the build script an answer for —
 * each commented with *why*, not just *what*, so a future Wiktionary dump
 * that starts covering one can have its entry deleted rather than
 * silently kept stale. Never overrides a lemma `derivedData` already
 * resolves correctly (see the merge below) — this is a set of gaps to
 * fill, not a correction layer sitting in front of the general mechanism
 * (that pattern was tried and reverted for historical-kana readings; the
 * lesson applies here too). */
const RESIDUAL: Record<string, LexiconEntry> = {
  // 曰: two distinct uses, both needing a hand-supplied answer since
  // Wiktionary has no verb entry for 曰 at all (regardless of sense).
  // Introducing reported speech (子曰：「...」), 曰はく is a fixed -aku
  // nominalization, not a conjugating verb — `fixedReading` bypasses
  // conjugation entirely for that case (see `isNamingUse` in
  // conjugationContext.ts for how the dispatch tells the two apart). Used
  // instead as a plain naming verb (名曰軒轅, "[his] name was Xuanyuan" —
  // not a quotation), it conjugates normally as いふ/いう, the same 四段ハ行
  // class as 言ふ/謂ふ — `conjClass` covers that case. kanjidic's own
  // いわ.く is the *modern* spelling (わ, not は) and splits at the wrong
  // boundary for the fixedReading case besides, so `reading` is supplied
  // directly rather than deferring to it either way.
  曰: { fixedReading: "はく", conjClass: "yodan-ha", reading: "い" },

  // よろこばし ("pleased") — Wiktionary's 悦/説/悦ばしい pages are all
  // soft-redirects with no conjugation data, and 説 itself only has an
  // entry for its unrelated と.く ("to explain") sense.
  說: { conjClass: "shiku-keiyoushi", okuriganaPrefix: "ば", reading: "よろこ" },
  説: { conjClass: "shiku-keiyoushi", okuriganaPrefix: "ば", reading: "よろこ" },
  悦: { conjClass: "shiku-keiyoushi", okuriganaPrefix: "ば", reading: "よろこ" },

  // 慍む (上二段マ行, "to resent") — no modern reflex in Wiktionary at all;
  // this sense didn't survive into contemporary Japanese vocabulary.
  慍: { conjClass: "kami-nidan-ma", reading: "うら" },

  // 謂ふ ("to call/say X") — "謂う" is a soft-redirect with no data; same
  // は行四段 row as 言ふ, which does have a full attested table.
  謂: { conjClass: "yodan-ha", reading: "い" },

  // 為す ("to do/make") — "為す"/"爲す" are soft-redirects; さ変 is the
  // well-known irregular class for this word regardless.
  爲: { conjClass: "sa-hen", reading: "な" },
  為: { conjClass: "sa-hen", reading: "な" },

  // 成る ("to become") — a genuine homograph the build script can't resolve
  // on its own: 成/為 are *both* attested kanji spellings of two different
  // kana-headword verbs, なる ("to become", 四段ラ行) and なす ("to do/make",
  // 四段サ行 — な+す, unrelated to 為す above despite the same kanji), each
  // only reachable via its kana entry's own "kanji"-tagged alternate forms,
  // not a direct kanji-headword page of its own. Whichever entry the build
  // script happens to reach first for a given kanji wins by construction
  // (see its own doc) — for 成 that was なす, giving the wrong sense for
  // 成而聰明 ("becoming wise", 成る, not "making [something]"). 為 doesn't
  // need its own residual line for this, since it already has the sa-hen
  // one above (為す, not なる, is the standard kundoku sense there).
  成: { conjClass: "yodan-ra", reading: "な" },

  // 来たる ("to arrive from afar") — the build script's own derived answer
  // for 來/来 is also correct 四段ラ行 with the correct full reading きた,
  // but this app's kanbun-kundoku convention shows たる visibly as okurigana
  // (来たる) rather than folding it into the furigana (来る read きたる) the
  // way Wiktionary's own bungo-table forms (來ら/來り, kanji alone covering
  // the whole きた) do — a *typesetting* convention difference, not a
  // conjugation-class disagreement, so only the reading/okurigana split
  // changes here, not the class itself.
  來: { conjClass: "yodan-ra", okuriganaPrefix: "た", reading: "き" },
  来: { conjClass: "yodan-ra", okuriganaPrefix: "た", reading: "き" },

  // 往ぬ ("to go/depart") — soft-redirect, no data; classical grammar has
  // exactly two ナ変 verbs (死ぬ/往ぬ), 死 already resolves via Wiktionary.
  往: { conjClass: "na-hen", reading: "い" },

  // 取る ("to take") — itself a soft-redirect with no data; only its modern
  // compounds (取り戻す etc.) have full entries, none in the plain row.
  取: { conjClass: "yodan-ra", reading: "と" },

  // 種う ("to plant", 種樹 "to plant trees") — ワ行下二段, the same word as
  // 植う and spelled with it in modern Japanese (植える). Wiktionary files the
  // word under 植 and has no verb entry for 種 at all, so the build script
  // derives 植 correctly and 種 not at all; `SUPPLEMENTARY_KUN` in
  // `kanjidicLookup.ts` supplies the reading う (KANJIDIC2 lists only the
  // noun たね and the on'yomi), but a reading with no class conjugates
  // nowhere — 種樹 came out 樹を種, the bare character with no ending.
  //
  // The class could not even be *written* here until ワ行下二段 existed:
  // `readingResolver.ts` refuses to derive any あ-row -eru mechanically,
  // because 得る/見える/植える have collapsed onto one え in modern spelling,
  // and ゑ is exactly the distinction that recovers this one — 種ゑて, not
  // 種えて.
  種: { conjClass: "shimo-nidan-wa", reading: "う" },

  // 貰ふ ("to receive", 需何藥 "what medicine [do I] get") — ハ行四段:
  // もらは/もらひ/もらふ/もらふ/もらへ. Chosen by the reader, who was asked;
  // it is not a dictionary's claim about 需 and no source attests it. Every
  // other entry in this table corrects a *sense* Wiktionary got wrong for a
  // word it does hold; this one is a word the reader has assigned to a
  // character, and it is here for the same mechanical reason 種 above is: the
  // reading is supplied by `SUPPLEMENTARY_KUN` in `kanjidicLookup.ts`
  // (KANJIDIC2's entry for 需 lists no kun'yomi whatever, only ジュ), and a
  // reading with no class conjugates nowhere — 需 printed もらふ in every
  // position, 未然形 and 已然形 alike. That file's own doc carries the rest of
  // the argument, including why both tables are needed rather than either
  // one.
  需: { conjClass: "yodan-ha", reading: "もら" },

  // 仁なり ("to be benevolent") — ナリ活用形容動詞. This parser tags a stative
  // predicate `Degree=Pos` — VERB up to 0.3.1, **ADJ** from 0.3.2, both of
  // which `usesLexiconEntry` admits — and 仁 is one of the commonest in the
  // corpus (仁者, 仁人, 君子仁也), but KANJIDIC gives 仁 *no kun'yomi at all*:
  // it is a Sino-Japanese abstract noun, read on'yomi and predicated with なり.
  // With no reading to inflect, 仁者 came out 仁もの where kundoku wants
  // 仁なる者 — the 連体形 rule fired correctly and had no paradigm to select
  // from. 賢 needs nothing here because it has a real kun'yomi (さかし) and
  // conjugates as シク活用 already.
  //
  // Only 仁. The same shape covers 義/禮/智/信 and every other kun-less virtue
  // noun, and each is a separate claim about how that word is read
  // predicatively rather than one rule — listed here so the next one is an
  // addition, not a rediscovery.
  仁: { conjClass: "nari-keiyoudoushi", reading: "じん" },

  // 少なし ("few") — modern 少ない has no classical table (its "ない" is a
  // separate modern negative-adjective suffix, not this word's own okurigana).
  少: { conjClass: "ku-keiyoushi", reading: "すくな" },

  // 挺く ("to spring back straight") — Wiktionary's only 挺す entry is the
  // unrelated on'yomi sense ていす ("to nominate oneself"), さ変; kanjidic's
  // sole attested kun'yomi for this sense is 抜く-shaped ぬ.く, a documented
  // best-effort guess (see the app's own reading-resolution notes), not a
  // confirmed traditional kundoku for this specific line.
  挺: { conjClass: "yodan-ka", reading: "ぬ" },

  // 博し ("broad, extensive") — no plain adjective entry at all in
  // Wiktionary; only na-adjective compounds (博学/博識/博雅) exist.
  博: { conjClass: "ku-keiyoushi", reading: "ひろ" },

  // 磨く ("to grind/polish", 金就礪則利's 礪) — has no entry at all (derived
  // or otherwise): kanjidic lists it under 磨/研, not this variant kanji, and
  // Wiktionary's own page for this word never lists 礪 among its spellings.
  // 四段カ行, the regular class for a plain -く verb like this.
  礪: { conjClass: "yodan-ka", reading: "みが" },

  // 無し ("there is not") — the derived entry for 無/无 is 為す's homophone
  // なす ("to do/make", a real but unrelated word also spelled 成す/為す),
  // the same cross-entry ambiguity as 成/為/成 above: 無 and 无 are both
  // attested kanji spellings of なす's kana headword too, and that entry
  // wins the extraction script's first-match race. ク活用, not a verb at
  // all — 無き人 (rentai), 無し (shuushi), matching real kanbun convention
  // (overrides.json's own contextPos:["VERB"] "なし" entry for this same
  // character is consequently never reached, since VERB_LEXICON is checked
  // first whenever pos is VERB — this residual entry is what actually fixes
  // it, not that override).
  無: { conjClass: "ku-keiyoushi", reading: "な" },
  无: { conjClass: "ku-keiyoushi", reading: "な" },

  // 戰/戦: three unrelated Japanese verbs share this spelling — たたかふ
  // "to fight" (四段ハ), をののく "to tremble" (四段カ) and そよぐ "to
  // rustle" (四段ガ) — and the build script, which takes the first entry
  // it can classify, lands on をののく. In kanbun the character is the
  // ordinary word for fighting or waging war; the trembling sense is a
  // different word that happens to be written the same way. The same
  // false-positive-on-another-sense case as 説/說 above, not mere
  // uncertainty. The class and reading match 闘/鬪, which the script
  // already resolves correctly for the same meaning.
  戰: { conjClass: "yodan-ha", reading: "たたか" },
  戦: { conjClass: "yodan-ha", reading: "たたか" },

  // 用ゐる ("to need, to require" — 俱言不須, "both said it was not needed"),
  // 上一段ワ行, the identical entry the build script derives for 用 itself.
  //
  // Here because of what 須's *other* use does to its dictionary entry. 須 is
  // a 再読文字, すべからく…べし, and KANJIDIC2's kun list for it leads with that
  // construction's own adverb: すべから.く, もち.いる, もと.める, in that order.
  // `pickKun` takes the first *dotted* reading for a VERB, so every 須 the
  // re-read rule declines — which, since `isRereadUse` now requires a governed
  // predicate, is every 須 with no verb under it — fell to すべから+く and read
  // 不須 as 須くず: the adverbial half of the very construction that had just
  // been ruled out, standing where a predicate belongs.
  //
  // The verb sense is the second dotted kun, and it is the one kanbun wants of
  // a bare 須. Stated here rather than by teaching the lookup to skip a
  // 再読文字's own adverb, because the reading and its class are what this
  // table is for and because the entry is checked ahead of KANJIDIC2 by both
  // panels at once — the re-read branch runs before either of them, so 須學 is
  // untouched and still reads すべからく學ぶべし.
  須: { conjClass: "kami-ichidan", okuriganaPrefix: "ゐ", reading: "もち" },

  // 出づ ("to come out, to emerge" — 哇有物出, "he retched, and there was
  // something that came out"), 下二段ダ行: 出で / 出で / 出づ / 出づる / 出づれ /
  // 出でよ.
  //
  // The same first-match-wins race 成/為 and 戰 above lose, not a gap: the build
  // script *does* classify 出, five times over (だす 四段サ行, でる twice, and
  // いづ/いず 下二段), and the sense it happens to reach first is the transitive
  // だす. In kanbun the character is the ordinary intransitive word for coming
  // out or emerging, and the transitive 出だす is the marked one. Wiktionary's
  // own 下二段ダ行 table for the word is the fourth entry in that list, so this
  // corrects which sense leads and states nothing the derived data does not
  // already hold.
  //
  // It is also what `nominalizedCandidates` in `reading/kanjidicLookup.ts`
  // nominalises, and the reason that function asks the lexicon before it asks
  // KANJIDIC2: 出's kun list leads with で.る, whose bare る `classicalConjClass`
  // can only read as 四段ラ行, so a 連体形 taken off the list would be 出る where
  // the word is 出づる.
  出: { conjClass: "shimo-nidan-da", reading: "い" },

  // 覺ゆ ("to feel, to perceive" — 忽覺咽中暴癢, "suddenly felt a violent itching
  // in his throat"), ヤ行下二段: 覺え / 覺え / 覺ゆ / 覺ゆる / 覺ゆれ / 覺えよ.
  //
  // The same first-match-wins race 出 above loses, and it loses it to a word of
  // the opposite valency: the build script classifies the character exactly
  // once, as さます (四段サ行, 覚ます "to wake [something] up"), and that is what
  // led. In kanbun 覺 is the ordinary intransitive word for feeling or noticing
  // something in oneself, and 覺ます — waking another thing up — is the marked
  // one. 忽覺咽中暴癢 read 忽ち癢を覺ます, which says he woke the itch up.
  //
  // **Both senses survive this**, and the さます one has to: RESIDUAL is
  // prepended to a kanji's derived senses rather than put in their place (see
  // `LEXICON_SENSES`), so 覚ます stays in the list behind 覺ゆ, where a 覺 that
  // really does read さ still reaches it. This entry moves which sense leads; it
  // discards nothing.
  //
  // **It is also the sense a reader's own picked reading had no way to find.**
  // `attestedSenseByModernSpelling` at the foot of this file is what the
  // picked-reading path in `conjugationContext.ts` asks when the *shape* of an
  // okurigana settles no paradigm, and a bare える settles none — ア行, ヤ行 and
  // ワ行 下二段 have all collapsed onto it in modern spelling, the same wall 種's
  // entry above documents. A hand-picked `Reading=おぼ|Okurigana=える` therefore
  // had nothing to match: JMdict holds only the modern 一段 覚える, and the
  // derived さます shares neither the reading nor the modern spelling. So the
  // pick was frozen at its citation form 覺える where its coordination chain
  // wants the 連用形 覺え. `modernOkurigana` of ヤ行下二段 is える exactly, which
  // is what makes this entry reachable by that lookup rather than merely
  // present.
  覺: { conjClass: "shimo-nidan-ya", reading: "おぼ" },
  覚: { conjClass: "shimo-nidan-ya", reading: "おぼ" },

  // 暴かなり ("sudden, violent" — 忽覺咽中暴癢, "suddenly felt a violent itching
  // in his throat") — ナリ活用形容動詞: にはかなら / にはかに / にはかなり /
  // にはかなる / にはかなれ. The same shape as 仁 above: a reading KANJIDIC2 does
  // not carry at all (its 暴 is あば.く / あば.れる, the modern "expose" and
  // "rave"), supplied by `SUPPLEMENTARY_KUN` in `reading/kanjidicLookup.ts`,
  // with the paradigm here because a supplementary kun derives none by itself.
  // The reader has settled the word; the derived 四段カ行 あばく is a real but
  // different word, and it survives in `LEXICON_SENSES` behind this one.
  //
  // **What this entry reaches and what it does not.** Both panels consult the
  // lexicon only for a token `usesLexiconEntry` admits — VERB, ADJ, AUX, a
  // converb, and two named mis-taggings — so it inflects a 暴 tagged VERB (as
  // this reader's earlier trees had it) or the ADJ parser 0.3.2 gives the same
  // word, and not the ADV the current tree has. For
  // that one the 連用形 に comes from the resolver instead, which is right for
  // an adverb and is all an adverb ever needs; see `adverbialCopulaEnding` in
  // `reading/readingResolver.ts`. Making the ADV case go through the paradigm
  // as well is a change to `usesLexiconEntry`, not to this table.
  暴: { conjClass: "nari-keiyoudoushi", reading: "にはか" },

  // 縶る ("to tie up, to tether" — 縶手足, "binds his hands and feet"),
  // 四段ラ行: 縶ら / 縶り / 縶る / 縶る / 縶れ / 縶れ.
  //
  // Not uncertainty about a paradigm but a different *word*. KANJIDIC2 gives
  // 縶 one kun'yomi, つな.ぐ ("to tether"), and the build script has no
  // Japanese entry for the character at all — it is rare enough that
  // Wiktionary's Japanese data covers neither reading — so every 縶 fell to
  // the generic kanjidic path and read 縶ぐ. The reader wants しばる, which is
  // the ordinary word for binding a person, and 縶手足 is binding a person.
  // The same false-positive-on-another-sense shape as 說/戰 above.
  //
  // Its reading is also listed in `SUPPLEMENTARY_KUN` (kanjidicLookup.ts), and
  // it takes both tables for the reason 需's entry documents there: this one
  // holds the paradigm both panels conjugate through, that one makes しばル a
  // kun candidate so the furigana menu offers it beside kanjidic's own つなグ.
  縶: { conjClass: "yodan-ra", reading: "しば" },

  // 貯ふ ("to store up, to lay in" — 甕中貯水, "stores water in a jar"),
  // ハ行下二段: 貯へ / 貯へ / 貯ふ / 貯ふる / 貯ふれ / 貯へよ.
  //
  // **Which of two kanjidic kun'yomi leads, and what the ending then is.**
  // KANJIDIC2 gives 貯 た.める and たくわ.える, in that order, and `pickKun`
  // takes the first *dotted* reading for a VERB — so every 貯 read た+める,
  // whose める `classicalVerbEnding` converts to む: 貯む, 下二段マ行. The word
  // wanted here is the second one, 蓄ふ/貯ふ, and choosing between two real
  // readings of a character by sense is what this table is for.
  //
  // The reading is written **たくは**, historically, and that is not
  // decoration: it is the only place the historical spelling can come from.
  // The 歴史的仮名遣い index has nothing for 貯 but its on'yomi (ちょ -> ちよ),
  // no other character attests たくわ for `historicalByReading` to transfer
  // from, and `fullSizeKana` touches neither わ nor は — so the kanjidic path
  // can only ever print the modern たくわ. `lexiconFurigana` in KundokuView.ts
  // draws this string directly, which is the whole reason the lexicon's
  // readings are historical.
  //
  // ハ行下二段 rather than ワ行/ア行: the modern 貯える is a 下一段 verb whose
  // え descends from へ (ハ行転呼), the same shape 答ふ/與ふ/教ふ have, and
  // `classicalVerbEnding` refuses the whole あ row on its own for exactly the
  // reason this entry settles it by hand — a modern -eる could be ア行, ヤ行,
  // ワ行 or (through 転呼) ハ行, and the surface form cannot tell them apart.
  //
  // **It is also what a hand-picked たくわ+える reaches**, through
  // `attestedSenseByModernSpelling` at the foot of this file:
  // `modernOkurigana` of ハ行下二段 is える exactly, and the reading is
  // compared after the same modernisation, so the reader's own modern
  // spelling finds this classical sense. Without it a pick carrying the あ-row
  // ending had no paradigm at all — `chosenConjClass` abstains on it by
  // design — and 甕中貯水 printed the modern 貯える in the middle of a
  // classical text.
  貯: { conjClass: "shimo-nidan-ha", reading: "たくは" },

  // 瘦す ("to grow thin" — 體漸瘦, "his body gradually wasted"), 下二段サ行:
  // 瘦せ / 瘦せ / 瘦す / 瘦する / 瘦すれ / 瘦せよ.
  //
  // **The ending was being derived from a mis-divided modern kun, and the
  // class read off the wrong half of it.** KANJIDIC2 writes 痩 as や.せる and
  // its 旧字体 瘦 as やせ.る — the same word with the dot in a different place
  // — and nothing downstream can see that the boundary moved. From やせ.る
  // the reading is やせ and the okurigana a bare る, which
  // `classicalVerbEnding` leaves alone (a one-kana ending is already
  // classical) and `classicalConjClass` reads as 四段ラ行, the only paradigm a
  // lone る states. So 體漸瘦 came out 瘦り — the 連用形 of a verb 瘦る that
  // does not exist. The word is 下二段サ行 痩す, whose 連用形 is the bare せ.
  //
  // Both spellings, because the mis-division is only on one of them and the
  // answer is the same word either way: 痩's や.せる would derive 下一段 せる ->
  // 下二段サ行 unaided, and giving it the entry costs nothing while leaving the
  // two forms of one character to be read by two different routes would.
  瘦: { conjClass: "shimo-nidan-sa", reading: "や" },
  痩: { conjClass: "shimo-nidan-sa", reading: "や" },

  // 適く ("to go to, to proceed to"), 四段カ行 — asked for by name.
  //
  // The same first-match-wins race 出 and 覺 above lose, and this one the
  // build script loses to a real second sense rather than to a gap: it
  // classifies 適 twice, かなふ (四段ハ行, "to suit, to accord with") and
  // てきす (サ変), and かなふ leads. Both are words; neither is the one a
  // kanbun reader takes a bare 適 for, which is ゆく.
  //
  // **This table alone, unlike 需 and 縶, and the difference is measured.**
  // Those two pair a `RESIDUAL` class with a `SUPPLEMENTARY_KUN` reading so the
  // furigana menu can offer it; 適 cannot have that half. KANJIDIC2's only kun
  // for the character is かな.う, so a supplementary ゆ.く would be its *second*
  // dotted reading — and `pickKun` sends a VERB through `pickByTransitivity`
  // as soon as there is more than one. That check, asked about a 適 with no
  // object, answers かな.う and reports `transitivitySelected`, which sets
  // `beatsLexicon` and stands this entry down: the character went on reading
  // かなふ, by a longer route. So the menu offers テキ and かなフ and not ゆク,
  // and the reading on the page is not one of its own entries.
  //
  // かなふ is not discarded. RESIDUAL is prepended to a kanji's derived senses
  // (see `LEXICON_SENSES`), so 適ふ stays in the list behind this, where a
  // reader who picks かな still reaches it — which is exactly what the tree
  // this was measured against does on its own 適 (`Reading=かな|Okurigana=う`).
  適: { conjClass: "yodan-ka", reading: "ゆ" },

  // 熾んなり ("blazing, in full spate" — 饞火上熾, "the fire of his craving rose
  // and blazed") — ナリ活用形容動詞: 熾んなら / 熾んに / 熾んなり / 熾んなる /
  // 熾んなれ, with ん as `okuriganaPrefix` because the stem's last mora is
  // written beside the character and not over it (盛ん is the same word and the
  // same division).
  //
  // The same pairing 需 and 縶 above make, and for the same two reasons. This
  // table holds the paradigm: KANJIDIC2 divides the reading (once
  // `SUPPLEMENTARY_KUN` supplies 盛's own dot for it) but an ん settles no
  // class, so without a line here さかん conjugates nowhere. `SUPPLEMENTARY_KUN`
  // holds the division: KANJIDIC2 writes 熾's third kun as the undivided さかん,
  // which its dot convention makes a bare noun, and `pickKun` drops every bare
  // reading for a token tagged VERB.
  //
  // The build script's own answer for 熾 is おこ 四段サ行 (熾す, "to build a
  // fire"), which survives behind this in `LEXICON_SENSES` — a real word, and a
  // transitive one, where 饞火上熾 has the fire itself as its subject.
  熾: { conjClass: "nari-keiyoudoushi", okuriganaPrefix: "ん", reading: "さか" },

  // みる, 上一段 — the same verb 見る is, written with the other character.
  // Wiktionary files 視 as a soft-redirect to 見 and the build script takes
  // nothing from it, so `derivedData` has 視 as `null` while 見 comes back with
  // four senses, `kami-ichidan` み among them.
  //
  // KANJIDIC2 already gives the *reading* (み.る), which is why this went
  // unnoticed: with no class the character still printed 視る, and 上一段's
  // 終止形 and 連体形 are both みる, so the two forms anything asked for came out
  // right by coincidence. 解縛視之 is what breaks the coincidence — the clause
  // is a temporal protasis, `decideConjForm` answers `izen`, and with nothing
  // to conjugate with the panel wrote the resolver's citation okurigana and
  // then the particle after it: 之を視るば. 已然形 みれ is the first form of this
  // paradigm that is not the citation one.
  //
  // Reading supplied beside the class, as 適 and 曰 do, so the entry states one
  // sense rather than pairing a class with whatever reading arrives.
  視: { conjClass: "kami-ichidan", reading: "み" },
};

const derived = derivedData as Record<string, LexiconEntry[]>;

/** Every classical sense the build script could classify for a kanji, in
 * confidence order — one kanji routinely spells two different words, and the
 * pair this app has to choose between at render time is the transitive/
 * intransitive one (肥 is こやす 四段サ行 when it has an object and こゆ
 * ヤ行下二段 when it doesn't). See the build script's own doc for how the
 * senses are derived and why the first one is the first one.
 *
 * RESIDUAL goes in front of a kanji's derived senses rather than replacing
 * them, for exactly the reason it wins in `VERB_LEXICON` below: its entries
 * correct a *misidentified sense*, and a misidentified sense is still a real
 * word the resolver may legitimately land on by its own reading (説's derived
 * 説く "to explain" is wrong for the よろこばし this app needs and right for
 * anything that actually reads と). Keeping both leaves the hand-supplied
 * answer first, where every existing caller sees it, without discarding
 * Wiktionary's. */
export const LEXICON_SENSES: Record<string, readonly LexiconEntry[]> = (() => {
  const senses: Record<string, LexiconEntry[]> = {};
  for (const [kanji, list] of Object.entries(derived)) senses[kanji] = [...list];
  for (const [kanji, entry] of Object.entries(RESIDUAL)) senses[kanji] = [entry, ...(senses[kanji] ?? [])];
  return senses;
})();

// RESIDUAL wins where both exist — every entry in it is there specifically
// because the build script's derived answer for that kanji (説/說's only
// modern entry is 説く "to explain", a same-spelling different-sense
// homograph of the よろこばし this app needs) is for the wrong word, not
// because it's merely uncertain. This is the opposite merge order from
// historical-kana's index (a hand table was tried *in front of* that
// general index and reverted — see readingResolver.ts): there, every
// kanji the general index covered had a genuinely correct answer already;
// here, `derived`'s coverage of these specific kanji is a false positive
// on an unrelated sense, not a lower-confidence version of the right one.
//
// Derived from `LEXICON_SENSES` rather than merged a second time, so the
// single-entry view and the full list can't drift: this is by construction
// each kanji's leading sense, which is the entry this table held back when
// the index carried one sense per kanji and nothing else.
export const VERB_LEXICON: Record<string, LexiconEntry> = Object.fromEntries(
  Object.entries(LEXICON_SENSES).map(([kanji, senses]) => [kanji, senses[0]]),
);

/** The senses of `lemma` whose own `reading` is `reading` — the by-reading
 * lookup a context-chosen reading needs, since it has already decided *which*
 * of a character's words is being read and only wants that one's conjugation
 * data back. Returns every match rather than one: a reading does not always
 * pick out a single sense (肥's こやす and こゆ are both こ, differing only in
 * their okurigana), and it is the caller that holds the further evidence to
 * separate them — see `syntheticLexiconEntry` in conjugationContext.ts.
 *
 * Empty for an unknown lemma or an absent reading, so a caller can treat "no
 * attested sense" and "no such kanji" identically; both mean the same thing
 * to it. */
export function lexiconSensesByReading(lemma: string, reading: string | undefined): readonly LexiconEntry[] {
  if (reading === undefined) return [];
  return (LEXICON_SENSES[lemma] ?? []).filter((sense) => sense.reading === reading);
}

/** The modern okurigana a classical paradigm surfaces as, which is the
 * spelling KANJIDIC2 is written in — the inverse of the modern-to-classical
 * derivation `reading/classicalEnding.ts` performs, and the thing that lets an
 * attested sense be checked against a reading taken off a kanjidic entry.
 *
 * Every regular family collapses the same way it historically did: 四段
 * became 五段 with its 終止形 intact (は行's ふ alone modernizing to う, 習ふ
 * -> 習う), and both 二段 families became 一段, keeping their mizen vowel and
 * taking る (肥ゆ's え -> 肥える, 立つ's て -> 立てる, 起く's き -> 起きる).
 * The irregulars all ended up in -る too (見る, 来る, 有る), except ナ変's 死ぬ.
 * 形容動詞 have no okurigana of this kind at all and return undefined.
 *
 * That the 二段 families gain a る here is what makes this direction — and not
 * the 終止形, which they share with 四段 of the same 行 — the one that
 * identifies a word: 立つ and 立てる are both 立 + つ in classical, and only
 * the modern spelling keeps them apart.
 *
 * Where this guesses wrong it fails *closed* — a sense whose modern spelling
 * doesn't match is simply not taken, leaving the caller exactly where it was
 * without one — which is why サ変 is given the する that covers 爲/為 rather
 * than the す that would also fit 為す. */
export function modernOkurigana(sense: LexiconEntry): string | undefined {
  const conjClass = sense.conjClass;
  if (!conjClass) return undefined;
  const prefix = sense.okuriganaPrefix ?? "";
  if (conjClass === "ku-keiyoushi") return modernKana(prefix + "い");
  if (conjClass === "shiku-keiyoushi") return modernKana(prefix + "しい");
  if (conjClass === "nari-keiyoudoushi" || conjClass === "tari-keiyoudoushi") return undefined;
  if (conjClass.startsWith("kami-nidan-") || conjClass.startsWith("shimo-nidan-")) {
    return modernKana(prefix + conjugate(conjClass, "mizen") + "る");
  }
  if (conjClass.startsWith("yodan-")) return modernKana(prefix + conjugate(conjClass, "shuushi"));
  if (conjClass === "na-hen") return modernKana(prefix + "ぬ");
  return modernKana(prefix + "る");
}

/** The modern dictionary reading a classical word surfaces as, given its
 * paradigm and its own classical citation reading — `modernOkurigana` above
 * carried one mora further, from the ending to the whole headword.
 *
 * What it is for: a dictionary that holds classical words holds them under
 * their *classical* headword (JMdict lists 答ふ, こたう) while KANJIDIC2 holds
 * the same word under its modern one (答's こた.える). Neither can be looked up
 * in the other until one of them is converted, and this is the direction that
 * converts — the same many-to-one direction `modernKana` below is safe in, and
 * for the same reason (see its doc). The reverse, modern to classical, is the
 * one-to-many guess this whole file exists to avoid making.
 *
 * `classical` is the classical citation reading **as a modern dictionary
 * spells it**, which is what JMdict's own reading field holds: 答ふ is written
 * こたう there, not こたふ. So the ending stripped off it is
 * `modernKana(conjugate(conjClass, "shuushi"))` and not the 終止形 itself.
 * Returns undefined where `classical` does not end in that ending at all —
 * the paradigm and the reading are then not about the same word, and nothing
 * can be said.
 *
 * The stem this leaves is the kanji's own reading (こた), so the result is the
 * modern headword's reading (こたえる) — exactly the string a KANJIDIC2
 * kun'yomi's reading and okurigana make when joined. See
 * `classicalParadigmByModernReading` in `reading/jmdictLookup.ts`, which is
 * the one caller and which uses it to key an index. */
export function modernisedCitation(conjClass: ConjClass, classical: string): string | undefined {
  const okurigana = modernOkurigana({ conjClass });
  if (okurigana === undefined) return undefined;
  const shuushi = modernKana(conjugate(conjClass, "shuushi"));
  if (!classical.endsWith(shuushi)) return undefined;
  return classical.slice(0, classical.length - shuushi.length) + okurigana;
}

/** 歴史的仮名遣い to 現代仮名遣い, for okurigana only.
 *
 * The lexicon is written historically throughout and KANJIDIC2 is written
 * modernly, so the two spellings have to be brought into one before they can
 * be compared at all. Everything in an okurigana is word-*medial* by
 * construction — the kanji is in front of it — which is exactly the position
 * the three regular mergers apply in, and which is why this is a fixed table
 * rather than the undecidable modern-to-historical direction
 * `classicalConjugation.ts` warns about (that direction is one-to-many; this
 * one is many-to-one, and only ever run forwards).
 *
 *  - ハ行転呼: medial は行 became わ行/あ行 (習ふ -> 習う, 与へる -> 与える,
 *    変はる -> 変わる, 生ひる -> 生いる);
 *  - ワ行: ゐ/ゑ/を merged into い/え/お (用ゐる -> 用いる, 植ゑる -> 植える);
 *  - 四つ仮名: ぢ/づ merged into じ/ず (恥ぢる -> 恥じる).
 *
 * Without this the three rows added with `EXTRA_SUFFIX_OF` could never match
 * anything: ワ行下二段's own mizen ゑ built 植ゑる where KANJIDIC2 has 植える,
 * so 王植樹 went on reading the modern 植える even with 植う in the lexicon. */
function modernKana(okurigana: string): string {
  return [...okurigana].map((kana) => MEDIAL_KANA_MERGERS[kana] ?? kana).join("");
}

/** The same fold for a *reading*, which differs from an okurigana in exactly
 * one place: its first kana is word-initial, and ハ行転呼 is a word-*medial*
 * change. 早 はや and 舟 ふね keep their は行 initial; 貯 たくは becomes たくわ,
 * 帰 かへ becomes かえ, 沈 しづ becomes しず.
 *
 * The same rule, and the same exemption, `historicalKana.ts`'s own `modernKana`
 * applies when it keys an attestation by what a modern dictionary would call it
 * — written again here rather than imported so this file stays a leaf (its only
 * imports are `classicalConjugation.ts` and the generated index, which is what
 * lets `reading/classicalEnding.ts` import *it* without closing a cycle).
 *
 * Used for one thing: comparing a lexicon reading, which is historical, against
 * a reading that is modern — see `attestedSenseByModernSpelling`. It is
 * many-to-one and imperfect in that direction (続's つづ folds to つず where
 * modern spelling keeps つづく), and that costs nothing here, because a fold
 * that lands on a string no dictionary or menu ever produces simply matches no
 * query. What it must not do is *lose* an answer by turning one match into two,
 * and it does not: measured over the whole shipped index, no lemma has two
 * senses that collide only after folding. */
function modernReading(reading: string): string {
  return [...reading].map((kana, i) => (i === 0 ? kana : MEDIAL_KANA_MERGERS[kana] ?? kana)).join("");
}

const MEDIAL_KANA_MERGERS: Record<string, string> = {
  は: "わ", ひ: "い", ふ: "う", へ: "え", ほ: "お",
  ゐ: "い", ゑ: "え", を: "お",
  ぢ: "じ", づ: "ず",
};

/** The one sense of `lemma` that a *modern* citation spelling identifies —
 * reading plus the okurigana KANJIDIC2 writes after it — or undefined where
 * the lexicon's data does not settle the question.
 *
 * Both halves are needed and neither is enough. A reading alone is a stem,
 * and a stem is shared by words that are not the same word (悔 read く is
 * 悔いる to KANJIDIC2 and 悔む to Wiktionary; 見 read み is 見る, 見す and 見ゆ
 * all three). The okurigana alone says nothing about which character it
 * follows. Together they are the modern dictionary headword, which is exactly
 * what `pickKun`/`pickByTransitivity` had in hand when they chose it.
 *
 * More than one surviving candidate means the evidence does not identify the
 * word, so nothing is claimed — 射's 射る is attested both 上一段 and 四段ラ行
 * with the same reading い, and both spell themselves 射る today.
 *
 * **Both halves are compared modernly, and the reading half was not.** The
 * okurigana has gone through `modernKana` since this function existed — that is
 * what `modernOkurigana` is — while the reading was matched against the
 * lexicon's own spelling, which is 歴史的仮名遣い throughout. For most words the
 * two coincide and the omission was invisible; where they do not, this function
 * answered nothing about a word it holds. 貯 is the case that showed it: its
 * sense is `たくは` + ハ行下二段, whose modern citation spelling is たくわえる
 * exactly, and a reader who picked KANJIDIC2's own たくわ.える off the furigana
 * menu was asking about that very word under that very spelling and being told
 * the lexicon knew of none — so the pick kept the あ-row ending `chosenConjClass`
 * can state no paradigm for, and 甕中貯水 printed the modern 貯える.
 *
 * `lexiconSensesByReading` is deliberately left alone: it is asked elsewhere
 * with a *classical* reading the resolver has already settled (see
 * `attestedSense` in conjugationContext.ts), where an exact match is the
 * question. This is the modern-spelling lookup, and the fold belongs to it. */
export function attestedSenseByModernSpelling(
  lemma: string,
  reading: string | undefined,
  okurigana: string | undefined,
): LexiconEntry | undefined {
  if (reading === undefined) return undefined;
  const matches = (LEXICON_SENSES[lemma] ?? []).filter(
    (sense) =>
      sense.reading !== undefined &&
      (sense.reading === reading || modernReading(sense.reading) === reading) &&
      modernOkurigana(sense) === okurigana,
  );
  return matches.length === 1 ? matches[0] : undefined;
}
