#!/usr/bin/env python3
"""How often the treebank writes each SUD relation — the relation menu's prior.

The three category menus are shaded twice: a **prior** drawn synchronously from
the treebank's own frequencies (``xposPrior`` and its two siblings in
``src/render/tokenInspector.ts``), and then, if the parser answers, a
**posterior** from the tagger conditioned on the token.  The relation menu had
only the second, and the consequence was reported by the reader twice: on a
CoNLL-U text — which is every shipped sample, and every upload — there is no
parser, ``scoreArc`` cannot answer, and the relation menu sits flat beside three
menus that are shaded.  It looked broken because it was the odd one out, not
because the shading had failed.

What was missing is this table.  ``xposPrior``'s own doc argues why a prior is
worth having where a posterior cannot be had, and every word of it applies:
a menu of 34 relations, unshaded, gives a reader looking for one nothing to
start from, where a shaded one starts them in the right half of the list.  What
a prior cannot do is say which relation is right *here*, and it never claimed
to.

**Counted over the same corpus and the same branch as the xpos inventory** —
``relabeled_ext.udep_ruled.punct.rulemerged.adjfix``, all three splits — so the
two priors are commensurable and a reader comparing a shaded 品詞 menu with a
shaded relation menu is comparing like with like.  See
``scripts/build-xpos-inventory.py``, whose shape this follows exactly.

**Subtypes are counted as themselves**, not folded into their base.  The menu
picks a subtype as its own value (``mod@tmod`` is a row's own segment with its
own ``data-value``), so ``mod`` and ``mod@tmod`` are two answers a reader
chooses between and each needs its own weight.  Folding them would shade every
segment of a row alike and say nothing about the choice actually on offer.

Run:

    python3 scripts/build-deprel-frequency.py

writes ``src/parse/deprel-frequency.json``.  Committed, because the app imports
it directly and a reader without the treebank must still get a shaded menu —
which is the whole point of a prior.
"""

from __future__ import annotations

import collections
import json
import os
import sys

TREEBANK = os.path.expanduser(
    "~/Linguistics/Tools/SUD-spaCy/assets_lzh/SUD_Classical_Chinese-Kyoto"
)
TREEBANK_TAG = "relabeled_ext.udep_ruled.punct.rulemerged.adjfix"
SPLITS = ("train", "dev", "test")

OUT = os.path.join(os.path.dirname(__file__), "..", "src", "parse", "deprel-frequency.json")

# The treebank writes the root relation lowercase and this app writes it upper
# — `Token.dep` is "ROOT" at a sentence's root, and the menu offers it that way.
# Normalised here rather than at the lookup so that the shipped table is keyed
# exactly as the menu's own `data-value`s are, and no consumer has to remember.
ROOT_IN = "root"
ROOT_OUT = "ROOT"


def rows(path: str):
    with open(path, encoding="utf-8") as handle:
        for line in handle:
            line = line.rstrip("\n")
            if not line or line.startswith("#") or "\t" not in line:
                continue
            cols = line.split("\t")
            if len(cols) < 8 or "-" in cols[0] or "." in cols[0]:
                continue
            yield cols


def main() -> int:
    counts: collections.Counter = collections.Counter()
    tokens = 0

    for split in SPLITS:
        path = f"{TREEBANK}/lzh_kyoto-sud-{split}.{TREEBANK_TAG}.conllu"
        if not os.path.exists(path):
            print(f"missing treebank split: {path}", file=sys.stderr)
            return 1
        for cols in rows(path):
            relation = cols[7]
            if relation == "_":
                continue
            counts[ROOT_OUT if relation == ROOT_IN else relation] += 1
            tokens += 1

    payload = {
        "_": (
            "Generated by scripts/build-deprel-frequency.py from the Kyoto SUD "
            f"treebank ({TREEBANK_TAG}, {len(SPLITS)} splits, {tokens} tokens). "
            "Do not edit by hand; see that script for what it is for."
        ),
        "tokens": tokens,
        # Descending, so the file reads as what it is and the commonest — the
        # denominator every weight is put over — is the first line of it.
        "relations": dict(counts.most_common()),
    }

    with open(OUT, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=1)
        handle.write("\n")

    print(f"{tokens} tokens, {len(counts)} relations")
    print(f"commonest: {counts.most_common(1)[0][0]} {counts.most_common(1)[0][1]}")
    print(f"rarest:    {counts.most_common()[-1][0]} {counts.most_common()[-1][1]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
