#!/usr/bin/env node
// Dev-time asset fetch: downloads the Noto Serif CJK families this app
// self-hosts (OFL) from Google Fonts' CSS API across the weights the type
// scale in src/render/typography.css actually uses, saves each
// unicode-range subset woff2 under public/fonts/<family-slug>/, and writes
// the matching @font-face rules (with local, relative src paths) to
// src/render/fonts.css. Not run at app runtime — run once (or whenever the
// family/weight list changes) and commit the resulting font files + CSS.
//
// Two families, deliberately: JP is the app's general face (all the
// Japanese reading apparatus — furigana, okurigana, kunten, the
// kakikudashi panel, UI), while TC supplies the *Literary Chinese* base
// characters, whose traditional glyph shapes the Japanese face renders
// with modern shinjitai-influenced forms. See --font-kanbun in
// typography.css.
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const WEIGHTS = [300, 400, 500, 600, 700, 900];
const FAMILIES = [
  { name: "Noto Serif JP", slug: "noto-serif-jp" },
  { name: "Noto Serif TC", slug: "noto-serif-tc" },
];
const OUT_CSS = path.resolve("src/render/fonts.css");
const CHROME_UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36";

async function fetchCss(family, weights) {
  const url = `https://fonts.googleapis.com/css2?family=${family.replace(/ /g, "+")}:wght@${weights.join(";")}&display=swap`;
  const res = await fetch(url, { headers: { "User-Agent": CHROME_UA } });
  if (!res.ok) throw new Error(`Google Fonts CSS fetch failed: ${res.status}`);
  return res.text();
}

function parseFaces(css) {
  const faces = [];
  const blockRe = /@font-face\s*{([^}]*)}/g;
  let m;
  while ((m = blockRe.exec(css))) {
    const block = m[1];
    const weight = Number(/font-weight:\s*(\d+)/.exec(block)?.[1]);
    const url = /url\((https:[^)]+)\)/.exec(block)?.[1];
    const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1]?.trim();
    if (weight && url && range) faces.push({ weight, url, range });
  }
  return faces;
}

async function main() {
  const cssLines = [
    "/* Generated by scripts/fetch-fonts.mjs — do not hand-edit.",
    " * Noto Serif JP + Noto Serif TC, self-hosted (SIL Open Font License",
    " * 1.1), subsetted by Google Fonts into per-unicode-range woff2 files so",
    " * a browser only downloads the glyph ranges actually used on the page.",
    " */",
    "",
  ];

  for (const { name, slug } of FAMILIES) {
    const outDir = path.resolve(`public/fonts/${slug}`);
    await mkdir(outDir, { recursive: true });
    const faces = parseFaces(await fetchCss(name, WEIGHTS));
    console.log(`${name}: ${faces.length} font-face subsets across ${WEIGHTS.length} weights.`);

    let i = 0;
    for (const { weight, url, range } of faces) {
      i += 1;
      const filename = `${slug}-${weight}-${i}.woff2`;
      const res = await fetch(url);
      if (!res.ok) {
        console.error(`  ! failed to fetch ${url}: ${res.status}`);
        continue;
      }
      await writeFile(path.join(outDir, filename), Buffer.from(await res.arrayBuffer()));
      cssLines.push(
        "@font-face {",
        `  font-family: "${name}";`,
        "  font-style: normal;",
        `  font-weight: ${weight};`,
        "  font-display: swap;",
        `  src: url("/fonts/${slug}/${filename}") format("woff2");`,
        `  unicode-range: ${range};`,
        "}",
        "",
      );
      if (i % 40 === 0) console.log(`  ...${i}/${faces.length}`);
    }
  }

  await writeFile(OUT_CSS, cssLines.join("\n"));
  console.log(`Wrote ${OUT_CSS}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
